// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/domain/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commands
type AddStockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStockCommand) Reset() {
	*x = AddStockCommand{}
	mi := &file_proto_domain_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockCommand) ProtoMessage() {}

func (x *AddStockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockCommand.ProtoReflect.Descriptor instead.
func (*AddStockCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *AddStockCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddStockCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockCommand) Reset() {
	*x = ReserveStockCommand{}
	mi := &file_proto_domain_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockCommand) ProtoMessage() {}

func (x *ReserveStockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockCommand.ProtoReflect.Descriptor instead.
func (*ReserveStockCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveStockCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveStockCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReleaseStockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockCommand) Reset() {
	*x = ReleaseStockCommand{}
	mi := &file_proto_domain_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockCommand) ProtoMessage() {}

func (x *ReleaseStockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockCommand.ProtoReflect.Descriptor instead.
func (*ReleaseStockCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseStockCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReleaseStockCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseStockCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductStockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockCommand) Reset() {
	*x = DeductStockCommand{}
	mi := &file_proto_domain_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockCommand) ProtoMessage() {}

func (x *DeductStockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockCommand.ProtoReflect.Descriptor instead.
func (*DeductStockCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeductStockCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeductStockCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeductStockCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Events
type StockAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AddedAt       string                 `protobuf:"bytes,3,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAddedEvent) Reset() {
	*x = StockAddedEvent{}
	mi := &file_proto_domain_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAddedEvent) ProtoMessage() {}

func (x *StockAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAddedEvent.ProtoReflect.Descriptor instead.
func (*StockAddedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *StockAddedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockAddedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockAddedEvent) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

type StockReservedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedAt    string                 `protobuf:"bytes,4,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReservedEvent) Reset() {
	*x = StockReservedEvent{}
	mi := &file_proto_domain_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReservedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReservedEvent) ProtoMessage() {}

func (x *StockReservedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReservedEvent.ProtoReflect.Descriptor instead.
func (*StockReservedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *StockReservedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockReservedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockReservedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockReservedEvent) GetReservedAt() string {
	if x != nil {
		return x.ReservedAt
	}
	return ""
}

type StockReleasedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReleasedAt    string                 `protobuf:"bytes,4,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReleasedEvent) Reset() {
	*x = StockReleasedEvent{}
	mi := &file_proto_domain_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReleasedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReleasedEvent) ProtoMessage() {}

func (x *StockReleasedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReleasedEvent.ProtoReflect.Descriptor instead.
func (*StockReleasedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *StockReleasedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockReleasedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockReleasedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockReleasedEvent) GetReleasedAt() string {
	if x != nil {
		return x.ReleasedAt
	}
	return ""
}

type StockDeductedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	DeductedAt    string                 `protobuf:"bytes,4,opt,name=deducted_at,json=deductedAt,proto3" json:"deducted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockDeductedEvent) Reset() {
	*x = StockDeductedEvent{}
	mi := &file_proto_domain_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDeductedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDeductedEvent) ProtoMessage() {}

func (x *StockDeductedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDeductedEvent.ProtoReflect.Descriptor instead.
func (*StockDeductedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *StockDeductedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockDeductedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockDeductedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockDeductedEvent) GetDeductedAt() string {
	if x != nil {
		return x.DeductedAt
	}
	return ""
}

// Snapshot
type InventorySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TotalStock    int32                  `protobuf:"varint,2,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	ReservedStock int32                  `protobuf:"varint,3,opt,name=reserved_stock,json=reservedStock,proto3" json:"reserved_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventorySnapshot) Reset() {
	*x = InventorySnapshot{}
	mi := &file_proto_domain_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySnapshot) ProtoMessage() {}

func (x *InventorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySnapshot.ProtoReflect.Descriptor instead.
func (*InventorySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *InventorySnapshot) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventorySnapshot) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *InventorySnapshot) GetReservedStock() int32 {
	if x != nil {
		return x.ReservedStock
	}
	return 0
}

// Response
type InventoryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TotalStock     int32                  `protobuf:"varint,2,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	ReservedStock  int32                  `protobuf:"varint,3,opt,name=reserved_stock,json=reservedStock,proto3" json:"reserved_stock,omitempty"`
	AvailableStock int32                  `protobuf:"varint,4,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_proto_domain_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_domain_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventoryResponse) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *InventoryResponse) GetReservedStock() int32 {
	if x != nil {
		return x.ReservedStock
	}
	return 0
}

func (x *InventoryResponse) GetAvailableStock() int32 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

var File_proto_domain_inventory_proto protoreflect.FileDescriptor

const file_proto_domain_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/domain/inventory.proto\x12\x10domain.inventory\"L\n" +
	"\x0fAddStockCommand\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"k\n" +
	"\x13ReserveStockCommand\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"k\n" +
	"\x13ReleaseStockCommand\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"j\n" +
	"\x12DeductStockCommand\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"g\n" +
	"\x0fStockAddedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x19\n" +
	"\badded_at\x18\x03 \x01(\tR\aaddedAt\"\x8b\x01\n" +
	"\x12StockReservedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vreserved_at\x18\x04 \x01(\tR\n" +
	"reservedAt\"\x8b\x01\n" +
	"\x12StockReleasedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vreleased_at\x18\x04 \x01(\tR\n" +
	"releasedAt\"\x8b\x01\n" +
	"\x12StockDeductedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vdeducted_at\x18\x04 \x01(\tR\n" +
	"deductedAt\"z\n" +
	"\x11InventorySnapshot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vtotal_stock\x18\x02 \x01(\x05R\n" +
	"totalStock\x12%\n" +
	"\x0ereserved_stock\x18\x03 \x01(\x05R\rreservedStock\"\xa3\x01\n" +
	"\x11InventoryResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vtotal_stock\x18\x02 \x01(\x05R\n" +
	"totalStock\x12%\n" +
	"\x0ereserved_stock\x18\x03 \x01(\x05R\rreservedStock\x12'\n" +
	"\x0favailable_stock\x18\x04 \x01(\x05R\x0eavailableStockB=Z;github.com/example/ec-event-driven/proto/domain/inventorypbb\x06proto3"

var (
	file_proto_domain_inventory_proto_rawDescOnce sync.Once
	file_proto_domain_inventory_proto_rawDescData []byte
)

func file_proto_domain_inventory_proto_rawDescGZIP() []byte {
	file_proto_domain_inventory_proto_rawDescOnce.Do(func() {
		file_proto_domain_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domain_inventory_proto_rawDesc), len(file_proto_domain_inventory_proto_rawDesc)))
	})
	return file_proto_domain_inventory_proto_rawDescData
}

var file_proto_domain_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_domain_inventory_proto_goTypes = []any{
	(*AddStockCommand)(nil),     // 0: domain.inventory.AddStockCommand
	(*ReserveStockCommand)(nil), // 1: domain.inventory.ReserveStockCommand
	(*ReleaseStockCommand)(nil), // 2: domain.inventory.ReleaseStockCommand
	(*DeductStockCommand)(nil),  // 3: domain.inventory.DeductStockCommand
	(*StockAddedEvent)(nil),     // 4: domain.inventory.StockAddedEvent
	(*StockReservedEvent)(nil),  // 5: domain.inventory.StockReservedEvent
	(*StockReleasedEvent)(nil),  // 6: domain.inventory.StockReleasedEvent
	(*StockDeductedEvent)(nil),  // 7: domain.inventory.StockDeductedEvent
	(*InventorySnapshot)(nil),   // 8: domain.inventory.InventorySnapshot
	(*InventoryResponse)(nil),   // 9: domain.inventory.InventoryResponse
}
var file_proto_domain_inventory_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_domain_inventory_proto_init() }
func file_proto_domain_inventory_proto_init() {
	if File_proto_domain_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domain_inventory_proto_rawDesc), len(file_proto_domain_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_inventory_proto_goTypes,
		DependencyIndexes: file_proto_domain_inventory_proto_depIdxs,
		MessageInfos:      file_proto_domain_inventory_proto_msgTypes,
	}.Build()
	File_proto_domain_inventory_proto = out.File
	file_proto_domain_inventory_proto_goTypes = nil
	file_proto_domain_inventory_proto_depIdxs = nil
}
