// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/domain/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commands
type RegisterUserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserCommand) Reset() {
	*x = RegisterUserCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserCommand) ProtoMessage() {}

func (x *RegisterUserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserCommand.ProtoReflect.Descriptor instead.
func (*RegisterUserCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserCommand) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserCommand) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserCommand) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateProfileCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileCommand) Reset() {
	*x = UpdateProfileCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileCommand) ProtoMessage() {}

func (x *UpdateProfileCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileCommand.ProtoReflect.Descriptor instead.
func (*UpdateProfileCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangePasswordCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordCommand) Reset() {
	*x = ChangePasswordCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordCommand) ProtoMessage() {}

func (x *ChangePasswordCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordCommand.ProtoReflect.Descriptor instead.
func (*ChangePasswordCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePasswordCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordCommand) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RecordLoginCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLoginCommand) Reset() {
	*x = RecordLoginCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLoginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLoginCommand) ProtoMessage() {}

func (x *RecordLoginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLoginCommand.ProtoReflect.Descriptor instead.
func (*RecordLoginCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{3}
}

func (x *RecordLoginCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordLoginCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordLoginCommand) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RecordLoginCommand) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RecordLogoutCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLogoutCommand) Reset() {
	*x = RecordLogoutCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLogoutCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLogoutCommand) ProtoMessage() {}

func (x *RecordLogoutCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLogoutCommand.ProtoReflect.Descriptor instead.
func (*RecordLogoutCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{4}
}

func (x *RecordLogoutCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordLogoutCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeactivateUserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserCommand) Reset() {
	*x = DeactivateUserCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserCommand) ProtoMessage() {}

func (x *DeactivateUserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserCommand.ProtoReflect.Descriptor instead.
func (*DeactivateUserCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeactivateUserCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ActivateUserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserCommand) Reset() {
	*x = ActivateUserCommand{}
	mi := &file_proto_domain_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserCommand) ProtoMessage() {}

func (x *ActivateUserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserCommand.ProtoReflect.Descriptor instead.
func (*ActivateUserCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{6}
}

func (x *ActivateUserCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Events
type UserCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreatedEvent) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreatedEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserCreatedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdatedEvent) Reset() {
	*x = UserUpdatedEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatedEvent) ProtoMessage() {}

func (x *UserUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatedEvent.ProtoReflect.Descriptor instead.
func (*UserUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserUpdatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserUpdatedEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserPasswordChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	ChangedAt     string                 `protobuf:"bytes,3,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPasswordChangedEvent) Reset() {
	*x = UserPasswordChangedEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPasswordChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPasswordChangedEvent) ProtoMessage() {}

func (x *UserPasswordChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPasswordChangedEvent.ProtoReflect.Descriptor instead.
func (*UserPasswordChangedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserPasswordChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPasswordChangedEvent) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserPasswordChangedEvent) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

type UserLoggedInEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LoggedAt      string                 `protobuf:"bytes,5,opt,name=logged_at,json=loggedAt,proto3" json:"logged_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoggedInEvent) Reset() {
	*x = UserLoggedInEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoggedInEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoggedInEvent) ProtoMessage() {}

func (x *UserLoggedInEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoggedInEvent.ProtoReflect.Descriptor instead.
func (*UserLoggedInEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserLoggedInEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoggedInEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserLoggedInEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserLoggedInEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UserLoggedInEvent) GetLoggedAt() string {
	if x != nil {
		return x.LoggedAt
	}
	return ""
}

type UserLoggedOutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LoggedAt      string                 `protobuf:"bytes,3,opt,name=logged_at,json=loggedAt,proto3" json:"logged_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoggedOutEvent) Reset() {
	*x = UserLoggedOutEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoggedOutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoggedOutEvent) ProtoMessage() {}

func (x *UserLoggedOutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoggedOutEvent.ProtoReflect.Descriptor instead.
func (*UserLoggedOutEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserLoggedOutEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoggedOutEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserLoggedOutEvent) GetLoggedAt() string {
	if x != nil {
		return x.LoggedAt
	}
	return ""
}

type UserDeactivatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeactivatedAt string                 `protobuf:"bytes,2,opt,name=deactivated_at,json=deactivatedAt,proto3" json:"deactivated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeactivatedEvent) Reset() {
	*x = UserDeactivatedEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeactivatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeactivatedEvent) ProtoMessage() {}

func (x *UserDeactivatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeactivatedEvent.ProtoReflect.Descriptor instead.
func (*UserDeactivatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserDeactivatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDeactivatedEvent) GetDeactivatedAt() string {
	if x != nil {
		return x.DeactivatedAt
	}
	return ""
}

type UserActivatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivatedAt   string                 `protobuf:"bytes,2,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivatedEvent) Reset() {
	*x = UserActivatedEvent{}
	mi := &file_proto_domain_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivatedEvent) ProtoMessage() {}

func (x *UserActivatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivatedEvent.ProtoReflect.Descriptor instead.
func (*UserActivatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserActivatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivatedEvent) GetActivatedAt() string {
	if x != nil {
		return x.ActivatedAt
	}
	return ""
}

// Snapshot
type UserSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSnapshot) Reset() {
	*x = UserSnapshot{}
	mi := &file_proto_domain_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSnapshot) ProtoMessage() {}

func (x *UserSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSnapshot.ProtoReflect.Descriptor instead.
func (*UserSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_domain_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSnapshot) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSnapshot) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSnapshot) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserSnapshot) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_domain_user_proto protoreflect.FileDescriptor

const file_proto_domain_user_proto_rawDesc = "" +
	"\n" +
	"\x17proto/domain/user.proto\x12\vdomain.user\"o\n" +
	"\x13RegisterUserCommand\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"C\n" +
	"\x14UpdateProfileCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"S\n" +
	"\x15ChangePasswordCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x8a\x01\n" +
	"\x12RecordLoginCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"M\n" +
	"\x13RecordLogoutCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"0\n" +
	"\x15DeactivateUserCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x13ActivateUserCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xad\x01\n" +
	"\x10UserCreatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"^\n" +
	"\x10UserUpdatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"w\n" +
	"\x18UserPasswordChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x03 \x01(\tR\tchangedAt\"\xa6\x01\n" +
	"\x11UserLoggedInEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tlogged_at\x18\x05 \x01(\tR\bloggedAt\"i\n" +
	"\x12UserLoggedOutEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tlogged_at\x18\x03 \x01(\tR\bloggedAt\"V\n" +
	"\x14UserDeactivatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0edeactivated_at\x18\x02 \x01(\tR\rdeactivatedAt\"P\n" +
	"\x12UserActivatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\factivated_at\x18\x02 \x01(\tR\vactivatedAt\"\xdc\x01\n" +
	"\fUserSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAtB8Z6github.com/example/ec-event-driven/proto/domain/userpbb\x06proto3"

var (
	file_proto_domain_user_proto_rawDescOnce sync.Once
	file_proto_domain_user_proto_rawDescData []byte
)

func file_proto_domain_user_proto_rawDescGZIP() []byte {
	file_proto_domain_user_proto_rawDescOnce.Do(func() {
		file_proto_domain_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domain_user_proto_rawDesc), len(file_proto_domain_user_proto_rawDesc)))
	})
	return file_proto_domain_user_proto_rawDescData
}

var file_proto_domain_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_domain_user_proto_goTypes = []any{
	(*RegisterUserCommand)(nil),      // 0: domain.user.RegisterUserCommand
	(*UpdateProfileCommand)(nil),     // 1: domain.user.UpdateProfileCommand
	(*ChangePasswordCommand)(nil),    // 2: domain.user.ChangePasswordCommand
	(*RecordLoginCommand)(nil),       // 3: domain.user.RecordLoginCommand
	(*RecordLogoutCommand)(nil),      // 4: domain.user.RecordLogoutCommand
	(*DeactivateUserCommand)(nil),    // 5: domain.user.DeactivateUserCommand
	(*ActivateUserCommand)(nil),      // 6: domain.user.ActivateUserCommand
	(*UserCreatedEvent)(nil),         // 7: domain.user.UserCreatedEvent
	(*UserUpdatedEvent)(nil),         // 8: domain.user.UserUpdatedEvent
	(*UserPasswordChangedEvent)(nil), // 9: domain.user.UserPasswordChangedEvent
	(*UserLoggedInEvent)(nil),        // 10: domain.user.UserLoggedInEvent
	(*UserLoggedOutEvent)(nil),       // 11: domain.user.UserLoggedOutEvent
	(*UserDeactivatedEvent)(nil),     // 12: domain.user.UserDeactivatedEvent
	(*UserActivatedEvent)(nil),       // 13: domain.user.UserActivatedEvent
	(*UserSnapshot)(nil),             // 14: domain.user.UserSnapshot
}
var file_proto_domain_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_domain_user_proto_init() }
func file_proto_domain_user_proto_init() {
	if File_proto_domain_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domain_user_proto_rawDesc), len(file_proto_domain_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_user_proto_goTypes,
		DependencyIndexes: file_proto_domain_user_proto_depIdxs,
		MessageInfos:      file_proto_domain_user_proto_msgTypes,
	}.Build()
	File_proto_domain_user_proto = out.File
	file_proto_domain_user_proto_goTypes = nil
	file_proto_domain_user_proto_depIdxs = nil
}
