// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/domain/cart.proto

package cartpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commands
type AddItemCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemCommand) Reset() {
	*x = AddItemCommand{}
	mi := &file_proto_domain_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemCommand) ProtoMessage() {}

func (x *AddItemCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemCommand.ProtoReflect.Descriptor instead.
func (*AddItemCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddItemCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddItemCommand) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type RemoveItemCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemCommand) Reset() {
	*x = RemoveItemCommand{}
	mi := &file_proto_domain_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemCommand) ProtoMessage() {}

func (x *RemoveItemCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemCommand.ProtoReflect.Descriptor instead.
func (*RemoveItemCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveItemCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ClearCartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartCommand) Reset() {
	*x = ClearCartCommand{}
	mi := &file_proto_domain_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartCommand) ProtoMessage() {}

func (x *ClearCartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartCommand.ProtoReflect.Descriptor instead.
func (*ClearCartCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{2}
}

func (x *ClearCartCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Events
type ItemAddedToCartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	AddedAt       string                 `protobuf:"bytes,6,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAddedToCartEvent) Reset() {
	*x = ItemAddedToCartEvent{}
	mi := &file_proto_domain_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAddedToCartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAddedToCartEvent) ProtoMessage() {}

func (x *ItemAddedToCartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAddedToCartEvent.ProtoReflect.Descriptor instead.
func (*ItemAddedToCartEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ItemAddedToCartEvent) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *ItemAddedToCartEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemAddedToCartEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ItemAddedToCartEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemAddedToCartEvent) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemAddedToCartEvent) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

type ItemRemovedFromCartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RemovedAt     string                 `protobuf:"bytes,4,opt,name=removed_at,json=removedAt,proto3" json:"removed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRemovedFromCartEvent) Reset() {
	*x = ItemRemovedFromCartEvent{}
	mi := &file_proto_domain_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRemovedFromCartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRemovedFromCartEvent) ProtoMessage() {}

func (x *ItemRemovedFromCartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRemovedFromCartEvent.ProtoReflect.Descriptor instead.
func (*ItemRemovedFromCartEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ItemRemovedFromCartEvent) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *ItemRemovedFromCartEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemRemovedFromCartEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ItemRemovedFromCartEvent) GetRemovedAt() string {
	if x != nil {
		return x.RemovedAt
	}
	return ""
}

type CartClearedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClearedAt     string                 `protobuf:"bytes,3,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartClearedEvent) Reset() {
	*x = CartClearedEvent{}
	mi := &file_proto_domain_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartClearedEvent) ProtoMessage() {}

func (x *CartClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartClearedEvent.ProtoReflect.Descriptor instead.
func (*CartClearedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartClearedEvent) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CartClearedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartClearedEvent) GetClearedAt() string {
	if x != nil {
		return x.ClearedAt
	}
	return ""
}

// Snapshot
type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_proto_domain_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CartSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         map[string]*CartItem   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartSnapshot) Reset() {
	*x = CartSnapshot{}
	mi := &file_proto_domain_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartSnapshot) ProtoMessage() {}

func (x *CartSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartSnapshot.ProtoReflect.Descriptor instead.
func (*CartSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_domain_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartSnapshot) GetItems() map[string]*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_domain_cart_proto protoreflect.FileDescriptor

const file_proto_domain_cart_proto_rawDesc = "" +
	"\n" +
	"\x17proto/domain/cart.proto\x12\vdomain.cart\"z\n" +
	"\x0eAddItemCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\"K\n" +
	"\x11RemoveItemCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\"+\n" +
	"\x10ClearCartCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb4\x01\n" +
	"\x14ItemAddedToCartEvent\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x19\n" +
	"\badded_at\x18\x06 \x01(\tR\aaddedAt\"\x8a\x01\n" +
	"\x18ItemRemovedFromCartEvent\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"removed_at\x18\x04 \x01(\tR\tremovedAt\"c\n" +
	"\x10CartClearedEvent\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"cleared_at\x18\x03 \x01(\tR\tclearedAt\"[\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"\xc4\x01\n" +
	"\fCartSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12:\n" +
	"\x05items\x18\x03 \x03(\v2$.domain.cart.CartSnapshot.ItemsEntryR\x05items\x1aO\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.domain.cart.CartItemR\x05value:\x028\x01B8Z6github.com/example/ec-event-driven/proto/domain/cartpbb\x06proto3"

var (
	file_proto_domain_cart_proto_rawDescOnce sync.Once
	file_proto_domain_cart_proto_rawDescData []byte
)

func file_proto_domain_cart_proto_rawDescGZIP() []byte {
	file_proto_domain_cart_proto_rawDescOnce.Do(func() {
		file_proto_domain_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domain_cart_proto_rawDesc), len(file_proto_domain_cart_proto_rawDesc)))
	})
	return file_proto_domain_cart_proto_rawDescData
}

var file_proto_domain_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_domain_cart_proto_goTypes = []any{
	(*AddItemCommand)(nil),           // 0: domain.cart.AddItemCommand
	(*RemoveItemCommand)(nil),        // 1: domain.cart.RemoveItemCommand
	(*ClearCartCommand)(nil),         // 2: domain.cart.ClearCartCommand
	(*ItemAddedToCartEvent)(nil),     // 3: domain.cart.ItemAddedToCartEvent
	(*ItemRemovedFromCartEvent)(nil), // 4: domain.cart.ItemRemovedFromCartEvent
	(*CartClearedEvent)(nil),         // 5: domain.cart.CartClearedEvent
	(*CartItem)(nil),                 // 6: domain.cart.CartItem
	(*CartSnapshot)(nil),             // 7: domain.cart.CartSnapshot
	nil,                              // 8: domain.cart.CartSnapshot.ItemsEntry
}
var file_proto_domain_cart_proto_depIdxs = []int32{
	8, // 0: domain.cart.CartSnapshot.items:type_name -> domain.cart.CartSnapshot.ItemsEntry
	6, // 1: domain.cart.CartSnapshot.ItemsEntry.value:type_name -> domain.cart.CartItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_domain_cart_proto_init() }
func file_proto_domain_cart_proto_init() {
	if File_proto_domain_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domain_cart_proto_rawDesc), len(file_proto_domain_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_cart_proto_goTypes,
		DependencyIndexes: file_proto_domain_cart_proto_depIdxs,
		MessageInfos:      file_proto_domain_cart_proto_msgTypes,
	}.Build()
	File_proto_domain_cart_proto = out.File
	file_proto_domain_cart_proto_goTypes = nil
	file_proto_domain_cart_proto_depIdxs = nil
}
