// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/domain/category.proto

package categorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commands
type CreateCategoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryCommand) Reset() {
	*x = CreateCategoryCommand{}
	mi := &file_proto_domain_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryCommand) ProtoMessage() {}

func (x *CreateCategoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryCommand.ProtoReflect.Descriptor instead.
func (*CreateCategoryCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryCommand) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCategoryCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCategoryCommand) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCategoryCommand) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryCommand) Reset() {
	*x = UpdateCategoryCommand{}
	mi := &file_proto_domain_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryCommand) ProtoMessage() {}

func (x *UpdateCategoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryCommand.ProtoReflect.Descriptor instead.
func (*UpdateCategoryCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCategoryCommand) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateCategoryCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryCommand) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateCategoryCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCategoryCommand) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateCategoryCommand) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeleteCategoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryCommand) Reset() {
	*x = DeleteCategoryCommand{}
	mi := &file_proto_domain_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryCommand) ProtoMessage() {}

func (x *DeleteCategoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryCommand.ProtoReflect.Descriptor instead.
func (*DeleteCategoryCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCategoryCommand) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

// Events
type CategoryCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCreatedEvent) Reset() {
	*x = CategoryCreatedEvent{}
	mi := &file_proto_domain_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCreatedEvent) ProtoMessage() {}

func (x *CategoryCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCreatedEvent.ProtoReflect.Descriptor instead.
func (*CategoryCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryCreatedEvent) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryCreatedEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryCreatedEvent) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CategoryCreatedEvent) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryCreatedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CategoryUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryUpdatedEvent) Reset() {
	*x = CategoryUpdatedEvent{}
	mi := &file_proto_domain_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUpdatedEvent) ProtoMessage() {}

func (x *CategoryUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUpdatedEvent.ProtoReflect.Descriptor instead.
func (*CategoryUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryUpdatedEvent) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryUpdatedEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryUpdatedEvent) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CategoryUpdatedEvent) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryUpdatedEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CategoryDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryDeletedEvent) Reset() {
	*x = CategoryDeletedEvent{}
	mi := &file_proto_domain_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDeletedEvent) ProtoMessage() {}

func (x *CategoryDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDeletedEvent.ProtoReflect.Descriptor instead.
func (*CategoryDeletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryDeletedEvent) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryDeletedEvent) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// Snapshot
type CategorySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySnapshot) Reset() {
	*x = CategorySnapshot{}
	mi := &file_proto_domain_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySnapshot) ProtoMessage() {}

func (x *CategorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySnapshot.ProtoReflect.Descriptor instead.
func (*CategorySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_domain_category_proto_rawDescGZIP(), []int{6}
}

func (x *CategorySnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategorySnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategorySnapshot) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategorySnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategorySnapshot) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CategorySnapshot) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategorySnapshot) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CategorySnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CategorySnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_domain_category_proto protoreflect.FileDescriptor

const file_proto_domain_category_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/domain/category.proto\x12\x0fdomain.category\"\x9d\x01\n" +
	"\x15CreateCategoryCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"\xbe\x01\n" +
	"\x15UpdateCategoryCommand\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"8\n" +
	"\x15DeleteCategoryCommand\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"\xdc\x01\n" +
	"\x14CategoryCreatedEvent\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xdc\x01\n" +
	"\x14CategoryUpdatedEvent\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"V\n" +
	"\x14CategoryDeletedEvent\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\tR\tdeletedAt\"\x83\x02\n" +
	"\x10CategorySnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAtB<Z:github.com/example/ec-event-driven/proto/domain/categorypbb\x06proto3"

var (
	file_proto_domain_category_proto_rawDescOnce sync.Once
	file_proto_domain_category_proto_rawDescData []byte
)

func file_proto_domain_category_proto_rawDescGZIP() []byte {
	file_proto_domain_category_proto_rawDescOnce.Do(func() {
		file_proto_domain_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domain_category_proto_rawDesc), len(file_proto_domain_category_proto_rawDesc)))
	})
	return file_proto_domain_category_proto_rawDescData
}

var file_proto_domain_category_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_domain_category_proto_goTypes = []any{
	(*CreateCategoryCommand)(nil), // 0: domain.category.CreateCategoryCommand
	(*UpdateCategoryCommand)(nil), // 1: domain.category.UpdateCategoryCommand
	(*DeleteCategoryCommand)(nil), // 2: domain.category.DeleteCategoryCommand
	(*CategoryCreatedEvent)(nil),  // 3: domain.category.CategoryCreatedEvent
	(*CategoryUpdatedEvent)(nil),  // 4: domain.category.CategoryUpdatedEvent
	(*CategoryDeletedEvent)(nil),  // 5: domain.category.CategoryDeletedEvent
	(*CategorySnapshot)(nil),      // 6: domain.category.CategorySnapshot
}
var file_proto_domain_category_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_domain_category_proto_init() }
func file_proto_domain_category_proto_init() {
	if File_proto_domain_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domain_category_proto_rawDesc), len(file_proto_domain_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_category_proto_goTypes,
		DependencyIndexes: file_proto_domain_category_proto_depIdxs,
		MessageInfos:      file_proto_domain_category_proto_msgTypes,
	}.Build()
	File_proto_domain_category_proto = out.File
	file_proto_domain_category_proto_goTypes = nil
	file_proto_domain_category_proto_depIdxs = nil
}
