apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]+)"'
          matcherType: regex
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: View Trace
