// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/domain/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commands
type PlaceOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderCommand) Reset() {
	*x = PlaceOrderCommand{}
	mi := &file_proto_domain_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderCommand) ProtoMessage() {}

func (x *PlaceOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderCommand.ProtoReflect.Descriptor instead.
func (*PlaceOrderCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderCommand) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PayOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderCommand) Reset() {
	*x = PayOrderCommand{}
	mi := &file_proto_domain_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderCommand) ProtoMessage() {}

func (x *PayOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderCommand.ProtoReflect.Descriptor instead.
func (*PayOrderCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{1}
}

func (x *PayOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ShipOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderCommand) Reset() {
	*x = ShipOrderCommand{}
	mi := &file_proto_domain_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderCommand) ProtoMessage() {}

func (x *ShipOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderCommand.ProtoReflect.Descriptor instead.
func (*ShipOrderCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{2}
}

func (x *ShipOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderCommand) Reset() {
	*x = CancelOrderCommand{}
	mi := &file_proto_domain_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderCommand) ProtoMessage() {}

func (x *CancelOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderCommand.ProtoReflect.Descriptor instead.
func (*CancelOrderCommand) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Shared types
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_domain_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Events
type OrderPlacedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	PlacedAt      string                 `protobuf:"bytes,5,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPlacedEvent) Reset() {
	*x = OrderPlacedEvent{}
	mi := &file_proto_domain_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPlacedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent) ProtoMessage() {}

func (x *OrderPlacedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderPlacedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPlacedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderPlacedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderPlacedEvent) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderPlacedEvent) GetPlacedAt() string {
	if x != nil {
		return x.PlacedAt
	}
	return ""
}

type OrderPaidEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaidAt        string                 `protobuf:"bytes,2,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaidEvent) Reset() {
	*x = OrderPaidEvent{}
	mi := &file_proto_domain_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaidEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaidEvent) ProtoMessage() {}

func (x *OrderPaidEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaidEvent.ProtoReflect.Descriptor instead.
func (*OrderPaidEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderPaidEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPaidEvent) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type OrderShippedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippedAt     string                 `protobuf:"bytes,2,opt,name=shipped_at,json=shippedAt,proto3" json:"shipped_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderShippedEvent) Reset() {
	*x = OrderShippedEvent{}
	mi := &file_proto_domain_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderShippedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderShippedEvent) ProtoMessage() {}

func (x *OrderShippedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderShippedEvent.ProtoReflect.Descriptor instead.
func (*OrderShippedEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderShippedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderShippedEvent) GetShippedAt() string {
	if x != nil {
		return x.ShippedAt
	}
	return ""
}

type OrderCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledAt   string                 `protobuf:"bytes,3,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelledEvent) Reset() {
	*x = OrderCancelledEvent{}
	mi := &file_proto_domain_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledEvent) ProtoMessage() {}

func (x *OrderCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledEvent.ProtoReflect.Descriptor instead.
func (*OrderCancelledEvent) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCancelledEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderCancelledEvent) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

// Snapshot
type OrderSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSnapshot) Reset() {
	*x = OrderSnapshot{}
	mi := &file_proto_domain_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSnapshot) ProtoMessage() {}

func (x *OrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domain_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSnapshot.ProtoReflect.Descriptor instead.
func (*OrderSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_domain_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderSnapshot) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderSnapshot) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_domain_order_proto protoreflect.FileDescriptor

const file_proto_domain_order_proto_rawDesc = "" +
	"\n" +
	"\x18proto/domain/order.proto\x12\fdomain.order\"[\n" +
	"\x11PlaceOrderCommand\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.domain.order.OrderItemR\x05items\",\n" +
	"\x0fPayOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"-\n" +
	"\x10ShipOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"G\n" +
	"\x12CancelOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"p\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\"\xa8\x01\n" +
	"\x10OrderPlacedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.domain.order.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1b\n" +
	"\tplaced_at\x18\x05 \x01(\tR\bplacedAt\"D\n" +
	"\x0eOrderPaidEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\apaid_at\x18\x02 \x01(\tR\x06paidAt\"M\n" +
	"\x11OrderShippedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"shipped_at\x18\x02 \x01(\tR\tshippedAt\"k\n" +
	"\x13OrderCancelledEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fcancelled_at\x18\x03 \x01(\tR\vcancelledAt\"\xd3\x01\n" +
	"\rOrderSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.domain.order.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAtB9Z7github.com/example/ec-event-driven/proto/domain/orderpbb\x06proto3"

var (
	file_proto_domain_order_proto_rawDescOnce sync.Once
	file_proto_domain_order_proto_rawDescData []byte
)

func file_proto_domain_order_proto_rawDescGZIP() []byte {
	file_proto_domain_order_proto_rawDescOnce.Do(func() {
		file_proto_domain_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domain_order_proto_rawDesc), len(file_proto_domain_order_proto_rawDesc)))
	})
	return file_proto_domain_order_proto_rawDescData
}

var file_proto_domain_order_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_domain_order_proto_goTypes = []any{
	(*PlaceOrderCommand)(nil),   // 0: domain.order.PlaceOrderCommand
	(*PayOrderCommand)(nil),     // 1: domain.order.PayOrderCommand
	(*ShipOrderCommand)(nil),    // 2: domain.order.ShipOrderCommand
	(*CancelOrderCommand)(nil),  // 3: domain.order.CancelOrderCommand
	(*OrderItem)(nil),           // 4: domain.order.OrderItem
	(*OrderPlacedEvent)(nil),    // 5: domain.order.OrderPlacedEvent
	(*OrderPaidEvent)(nil),      // 6: domain.order.OrderPaidEvent
	(*OrderShippedEvent)(nil),   // 7: domain.order.OrderShippedEvent
	(*OrderCancelledEvent)(nil), // 8: domain.order.OrderCancelledEvent
	(*OrderSnapshot)(nil),       // 9: domain.order.OrderSnapshot
}
var file_proto_domain_order_proto_depIdxs = []int32{
	4, // 0: domain.order.PlaceOrderCommand.items:type_name -> domain.order.OrderItem
	4, // 1: domain.order.OrderPlacedEvent.items:type_name -> domain.order.OrderItem
	4, // 2: domain.order.OrderSnapshot.items:type_name -> domain.order.OrderItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_domain_order_proto_init() }
func file_proto_domain_order_proto_init() {
	if File_proto_domain_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domain_order_proto_rawDesc), len(file_proto_domain_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domain_order_proto_goTypes,
		DependencyIndexes: file_proto_domain_order_proto_depIdxs,
		MessageInfos:      file_proto_domain_order_proto_msgTypes,
	}.Build()
	File_proto_domain_order_proto = out.File
	file_proto_domain_order_proto_goTypes = nil
	file_proto_domain_order_proto_depIdxs = nil
}
